-- 코드를 입력하세요

-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 
-- 동물의 ID와 이름을 
-- ID 순으로 조회

SELECT OUTS.ANIMAL_ID
     , OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
    LEFT JOIN ANIMAL_INS AS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;
