-- 생산일자 2022-05
-- 식품 ID, 식품 이름, 총매출 조회
-- 총매출 기준 내림차순, 식품 ID 기준 오름차순

SELECT O.PRODUCT_ID
     , PRODUCT_NAME
     , SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS O
    JOIN FOOD_PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 23:59:59'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID