/*
1. 2022년 10월에 작성된 게시글
2. 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
3. 댓글 작성일을 기준으로 오름차순, 게시글 제목을 기준으로 오름차순 정렬
*/
SELECT BOARD.TITLE
     , BOARD.BOARD_ID
     , REPLY.REPLY_ID
     , REPLY.WRITER_ID
     , REPLY.CONTENTS
     , DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
    JOIN USED_GOODS_REPLY AS REPLY
        ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;